export enum ROLES {
    ADMIN = "ADMIN",
    TEACHER = "TEACHER",
    ACCOUNT_EDITOR = "ACCOUNT_EDITOR",
    VIEWER = "VIEWER",
    ASSIGNMENT_EDITOR = "ASSIGNMENT_EDITOR",
    NEWS_EDITOR = "NEWS_EDITOR",
    ENTREPRISE_EDITOR = "ENTERPRISE_EDITOR",
    USER = "USER",
    PRIZE_EDITOR = "PRIZE_EDITOR",
}
